dasd,sysfs: fix musl build
The commit cd690bff1516b40fecd5ec4a7f6619e5bffc3cf0 adding musl support
was not enough to build lshw with musl.

dasd.cc: In function 'bool scan_dasd(hwNode&)':
dasd.cc:45:52: error: 'basename' was not declared in this scope
       dev_name = basename(devices.gl_pathv[dev_num]);

Use the same fix.

Fixes:
http://autobuild.buildroot.net/results/aa1/aa1c20866fda025167b0d220b316c7d85a1b9663

Signed-off-by: Romain Naour <romain.naour@gmail.com>