Fix musl build: basename() is in libgen.h
Build is failing with musl libc:

sysfs.cc:103:21: error: ‘basename’ was not declared in this scope
       "/devices/" + basename(path.c_str());

That's because basename() is in <libgen.h> on musl libc.

Also, its argument is not const, so add const_cast.

Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>